package com.htong.communication.dl645;

public enum Dl645FrameType {
	BASIC,ZAIHE_1,ZAIHE_2,ZAIHE_3,ZAIHE_4,WEIYI_1,WEIYI_2,WEIYI_3,WEIYI_4,IB_1,IB_2,IB_3,IB_4,POWER_1,POWER_2,POWER_3,POWER_4,PF_1,PF_2,PF_3,PF_4,DGT_1,DGT_2,DGT_3,DGT_4,ZXYG,FXYG,ZXWG,FXWG,SY_ZXYGZ,SY_FXYGZ,SY_ZXWGZ,SY_FXWGZ,XDY,XDL,SH_YGGL,SH_WGGL,GLYS,OTHER_D,XIANDY,PINLV,LXDL,LXDY,DLBPHD,DYBPHD
}
